[package]
name = "webp-animator"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dev-dependencies]
image = { version = "0.25.6", default-features = false, features = ["webp"] }
webp-animation = "0.9.0"
